on:
  pull_request:
  push:
    branches-ignore:
      - main

name: CI

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14.x']

    name: Test on Node v${{ matrix.node }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node modules
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
            npm-${{ matrix.node }}-

      - name: Install Dependencies
        run: npm install --ignore-scripts --pure-lockfile
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          CI: true

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Test
        run: npm run test --if-present
        env:
          CI: true
